baseURL = "http://ritasneki.ru/"
languageCode = "ru"
title = "RitaSneki.ru"
theme = "dream"

[params]
  author = "RitaSneki.ru"
  description = "Пастила, снеки и мясные чипсы в Санкт-Петербурге."
  motto = "Пастила, снеки и мясные чипсы. Вы можете оформить заказ написав мне в: "
  avatar = "/photos/avatar.jpg"
  whatsapp = "http://wa.me/79117641589"
  instagram = "https://instagr.am/ritasneki"
  telegram = "https://t.me/ritasneki"
  images = ["/photos/avatar.jpg"]
