baseURL = "http://ritasneki.ru/"
languageCode = "ru"
title = "RitaSneki.ru"
theme = "dream"

[params]
  author = "RitaSneki.ru"
  motto = "Натуральные пастила, снеки и мясные чипсы. Вы можете оформить заказ написав мне в: "
  avatar = "/photos/avatar.jpg"
  whatsapp = "http://wa.me/79117641589"
  instagram = "https://instagr.am/ritasneki"
  telegram = "tg://resolve?domain=ritasneki"
  # https://t.me/ritasneki
